/* Generated from public ZeldaWWHDDecomp/wwhd 47e1dbc3886cfd8233859dffd73efc41a04a9130.
 * Source: wwhd_src/include/d/d_camera.h; CC0-1.0 (public-wwhd-LICENSE).
 * Partial views: named scalar fields only; unknown fields remain bytes.
 * Source offset qualifications still apply; see the public source. */
#pragma once
#include "../wwhd_guest.h"
#ifndef WWHD_SDK_ASSERT
#ifdef __cplusplus
#define WWHD_SDK_ASSERT(x, message) static_assert(x, message)
#else
#define WWHD_SDK_ASSERT(x, message) _Static_assert(x, message)
#endif
#endif
WWHD_SDK_ASSERT(sizeof(void*) == 4, "SDK layouts require a 32-bit guest target");

typedef union cSGlobe_l {
    u8 bytes[0x8];
    struct __attribute__((packed)) { f32 mRadius; };
    struct __attribute__((packed)) { u8 _pad_mV[0x4]; s16 mV; };
    struct __attribute__((packed)) { u8 _pad_mU[0x6]; s16 mU; };
} cSGlobe_l;
WWHD_SDK_ASSERT(sizeof(cSGlobe_l) == 0x8, "cSGlobe_l size");
WWHD_SDK_ASSERT(__builtin_offsetof(cSGlobe_l, mRadius) == 0x0, "cSGlobe_l.mRadius");
WWHD_SDK_ASSERT(__builtin_offsetof(cSGlobe_l, mV) == 0x4, "cSGlobe_l.mV");
WWHD_SDK_ASSERT(__builtin_offsetof(cSGlobe_l, mU) == 0x6, "cSGlobe_l.mU");

typedef union camSphChkdata_l {
    u8 bytes[0x20];
    struct __attribute__((packed)) { u32 field_0x0; };
    struct __attribute__((packed)) { u8 _pad_field_0x4[0x4]; f32 field_0x4; };
} camSphChkdata_l;
WWHD_SDK_ASSERT(sizeof(camSphChkdata_l) == 0x20, "camSphChkdata_l size");
WWHD_SDK_ASSERT(__builtin_offsetof(camSphChkdata_l, field_0x0) == 0x0, "camSphChkdata_l.field_0x0");
WWHD_SDK_ASSERT(__builtin_offsetof(camSphChkdata_l, field_0x4) == 0x4, "camSphChkdata_l.field_0x4");

typedef union dCamForcusLine {
    u8 bytes[0x70];
    struct __attribute__((packed)) { u8 mEffectLine[0x38]; };
    struct __attribute__((packed)) { u8 _pad_m48[0x48]; u8 m48; };
    struct __attribute__((packed)) { u8 _pad_m49[0x49]; u8 m49; };
    struct __attribute__((packed)) { u8 _pad__4A[0x4A]; u8 _4A[2]; };
    struct __attribute__((packed)) { u8 _pad_m4C[0x4C]; s32 m4C; };
    struct __attribute__((packed)) { u8 _pad_m50[0x50]; s32 m50; };
    struct __attribute__((packed)) { u8 _pad_m54[0x54]; s32 m54; };
    struct __attribute__((packed)) { u8 _pad_m58[0x58]; u16 m58; };
    struct __attribute__((packed)) { u8 _pad_m5A[0x5A]; u16 m5A; };
    struct __attribute__((packed)) { u8 _pad_m5C[0x5C]; u16 m5C; };
    struct __attribute__((packed)) { u8 _pad_m5E[0x5E]; u16 m5E; };
    struct __attribute__((packed)) { u8 _pad_m60[0x60]; f32 m60; };
    struct __attribute__((packed)) { u8 _pad_m64[0x64]; f32 m64; };
    struct __attribute__((packed)) { u8 _pad_m68[0x68]; f32 m68; };
    struct __attribute__((packed)) { u8 _pad_m6C[0x6C]; f32 m6C; };
} dCamForcusLine;
WWHD_SDK_ASSERT(sizeof(dCamForcusLine) == 0x70, "dCamForcusLine size");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, mEffectLine) == 0x0, "dCamForcusLine.mEffectLine");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m48) == 0x48, "dCamForcusLine.m48");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m49) == 0x49, "dCamForcusLine.m49");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, _4A) == 0x4A, "dCamForcusLine._4A");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m4C) == 0x4C, "dCamForcusLine.m4C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m50) == 0x50, "dCamForcusLine.m50");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m54) == 0x54, "dCamForcusLine.m54");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m58) == 0x58, "dCamForcusLine.m58");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m5A) == 0x5A, "dCamForcusLine.m5A");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m5C) == 0x5C, "dCamForcusLine.m5C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m5E) == 0x5E, "dCamForcusLine.m5E");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m60) == 0x60, "dCamForcusLine.m60");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m64) == 0x64, "dCamForcusLine.m64");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m68) == 0x68, "dCamForcusLine.m68");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamForcusLine, m6C) == 0x6C, "dCamForcusLine.m6C");

typedef union dCamera_c {
    u8 bytes[0x8E0];
    struct __attribute__((packed)) { u32 mpCamera; };
    struct __attribute__((packed)) { u8 _pad_mActive[0x4]; u8 mActive; };
    struct __attribute__((packed)) { u8 _pad_mPause[0x5]; u8 mPause; };
    struct __attribute__((packed)) { u8 _pad__036[0x36]; u8 _036[2]; };
    struct __attribute__((packed)) { u8 _pad_mFovy[0x38]; f32 mFovy; };
    struct __attribute__((packed)) { u8 _pad_m064[0x64]; f32 m064; };
    struct __attribute__((packed)) { u8 _pad_m068[0x68]; s32 m068; };
    struct __attribute__((packed)) { u8 _pad__06E[0x6E]; u8 _06E[2]; };
    struct __attribute__((packed)) { u8 _pad_m07C[0x7C]; u32 m07C; };
    struct __attribute__((packed)) { u8 _pad_m080[0x80]; u32 m080; };
    struct __attribute__((packed)) { u8 _pad_m09C[0x9C]; f32 m09C; };
    struct __attribute__((packed)) { u8 _pad__0A2[0xA2]; u8 _0A2[2]; };
    struct __attribute__((packed)) { u8 _pad_mStageMapToolCameraIdx[0xE4]; s32 mStageMapToolCameraIdx; };
    struct __attribute__((packed)) { u8 _pad_m0E8[0xE8]; s32 m0E8; };
    struct __attribute__((packed)) { u8 _pad__0F8[0xF8]; u8 _0F8[8]; };
    struct __attribute__((packed)) { u8 _pad_m100[0x100]; u8 m100; };
    struct __attribute__((packed)) { u8 _pad_m101[0x101]; u8 m101; };
    struct __attribute__((packed)) { u8 _pad_m102[0x102]; u8 m102; };
    struct __attribute__((packed)) { u8 _pad__103[0x103]; u8 _103; };
    struct __attribute__((packed)) { u8 _pad_m108[0x108]; u32 m108; };
    struct __attribute__((packed)) { u8 _pad_m10C[0x10C]; s32 m10C; };
    struct __attribute__((packed)) { u8 _pad_m110[0x110]; u8 m110; };
    struct __attribute__((packed)) { u8 _pad__111[0x111]; u8 _111[3]; };
    struct __attribute__((packed)) { u8 _pad_m114[0x114]; s32 m114; };
    struct __attribute__((packed)) { u8 _pad_m118[0x118]; u32 m118; };
    struct __attribute__((packed)) { u8 _pad_m11C[0x11C]; u32 m11C; };
    struct __attribute__((packed)) { u8 _pad_mCameraID[0x120]; s32 mCameraID; };
    struct __attribute__((packed)) { u8 _pad_mPadId[0x124]; s32 mPadId; };
    struct __attribute__((packed)) { u8 _pad_mpPlayerActor[0x128]; u32 mpPlayerActor; };
    struct __attribute__((packed)) { u8 _pad_mpLockonTarget[0x12C]; u32 mpLockonTarget; };
    struct __attribute__((packed)) { u8 _pad_mLockOnActorId[0x130]; u32 mLockOnActorId; };
    struct __attribute__((packed)) { u8 _pad_mpLockonActor[0x134]; u32 mpLockonActor; };
    struct __attribute__((packed)) { u8 _pad_mForceLockTimer[0x138]; s32 mForceLockTimer; };
    struct __attribute__((packed)) { u8 _pad_mCurMode[0x13C]; s32 mCurMode; };
    struct __attribute__((packed)) { u8 _pad_mNextMode[0x140]; s32 mNextMode; };
    struct __attribute__((packed)) { u8 _pad_m144[0x144]; s32 m144; };
    struct __attribute__((packed)) { u8 _pad__14A[0x14A]; u8 _14A[2]; };
    struct __attribute__((packed)) { u8 _pad_m14C[0x14C]; f32 m14C; };
    struct __attribute__((packed)) { u8 _pad_m150[0x150]; f32 m150; };
    struct __attribute__((packed)) { u8 _pad_m154[0x154]; f32 m154; };
    struct __attribute__((packed)) { u8 _pad_mStickMainPosXLast[0x158]; f32 mStickMainPosXLast; };
    struct __attribute__((packed)) { u8 _pad_mStickMainPosYLast[0x15C]; f32 mStickMainPosYLast; };
    struct __attribute__((packed)) { u8 _pad_mStickMainValueLast[0x160]; f32 mStickMainValueLast; };
    struct __attribute__((packed)) { u8 _pad_mStickMainPosXDelta[0x164]; f32 mStickMainPosXDelta; };
    struct __attribute__((packed)) { u8 _pad_mStickMainPosYDelta[0x168]; f32 mStickMainPosYDelta; };
    struct __attribute__((packed)) { u8 _pad_mStickMainValueDelta[0x16C]; f32 mStickMainValueDelta; };
    struct __attribute__((packed)) { u8 _pad_mStickCPosXLast[0x170]; f32 mStickCPosXLast; };
    struct __attribute__((packed)) { u8 _pad_mStickCPosYLast[0x174]; f32 mStickCPosYLast; };
    struct __attribute__((packed)) { u8 _pad_mStickCValueLast[0x178]; f32 mStickCValueLast; };
    struct __attribute__((packed)) { u8 _pad_mStickCPosXDelta[0x17C]; f32 mStickCPosXDelta; };
    struct __attribute__((packed)) { u8 _pad_mStickCPosYDelta[0x180]; f32 mStickCPosYDelta; };
    struct __attribute__((packed)) { u8 _pad_mStickCValueDelta[0x184]; f32 mStickCValueDelta; };
    struct __attribute__((packed)) { u8 _pad_m184[0x188]; s32 m184; };
    struct __attribute__((packed)) { u8 _pad_m188[0x18C]; u32 m188; };
    struct __attribute__((packed)) { u8 _pad_m18C[0x190]; u32 m18C; };
    struct __attribute__((packed)) { u8 _pad_mTriggerLeftLast[0x194]; f32 mTriggerLeftLast; };
    struct __attribute__((packed)) { u8 _pad_mTriggerLeftDelta[0x198]; f32 mTriggerLeftDelta; };
    struct __attribute__((packed)) { u8 _pad_mHoldLockL[0x19C]; u8 mHoldLockL; };
    struct __attribute__((packed)) { u8 _pad_mTrigLockL[0x19D]; u8 mTrigLockL; };
    struct __attribute__((packed)) { u8 _pad_m19A[0x19E]; u8 m19A; };
    struct __attribute__((packed)) { u8 _pad_m19B[0x19F]; u8 m19B; };
    struct __attribute__((packed)) { u8 _pad_mTriggerRightLast[0x1A0]; f32 mTriggerRightLast; };
    struct __attribute__((packed)) { u8 _pad_mTriggerRightDelta[0x1A4]; f32 mTriggerRightDelta; };
    struct __attribute__((packed)) { u8 _pad_mHoldLockR[0x1A8]; u8 mHoldLockR; };
    struct __attribute__((packed)) { u8 _pad_mTrigLockR[0x1A9]; u8 mTrigLockR; };
    struct __attribute__((packed)) { u8 _pad_m1A6[0x1AA]; u8 m1A6; };
    struct __attribute__((packed)) { u8 _pad_m1A7[0x1AB]; u8 m1A7; };
    struct __attribute__((packed)) { u8 _pad_mHoldX[0x1AC]; u8 mHoldX; };
    struct __attribute__((packed)) { u8 _pad_mTrigX[0x1AD]; u8 mTrigX; };
    struct __attribute__((packed)) { u8 _pad_mHoldY[0x1AE]; u8 mHoldY; };
    struct __attribute__((packed)) { u8 _pad_mTrigY[0x1AF]; u8 mTrigY; };
    struct __attribute__((packed)) { u8 _pad_mHoldZ[0x1B0]; u8 mHoldZ; };
    struct __attribute__((packed)) { u8 _pad_mTrigZ[0x1B1]; u8 mTrigZ; };
    struct __attribute__((packed)) { u8 _pad_m1AE[0x1B2]; u8 m1AE; };
    struct __attribute__((packed)) { u8 _pad_m1AF[0x1B3]; u8 m1AF; };
    struct __attribute__((packed)) { u8 _pad__22A[0x22A]; u8 _22A[2]; };
    struct __attribute__((packed)) { u8 _pad_m248[0x24C]; s32 m248[3]; };
    struct __attribute__((packed)) { u8 _pad_m254[0x258]; s32 m254; };
    struct __attribute__((packed)) { u8 _pad_m258[0x25C]; s32 m258; };
    struct __attribute__((packed)) { u8 _pad_m314[0x318]; u8 m314; };
    struct __attribute__((packed)) { u8 _pad__319[0x319]; u8 _319[3]; };
    struct __attribute__((packed)) { u8 _pad_m318[0x31C]; f32 m318; };
    struct __attribute__((packed)) { u8 _pad_m31C[0x320]; u8 m31C; };
    struct __attribute__((packed)) { u8 _pad_m31D[0x321]; u8 m31D; };
    struct __attribute__((packed)) { u8 _pad__322[0x322]; u8 _322[2]; };
    struct __attribute__((packed)) { u8 _pad_m33C[0x340]; u32 m33C; };
    struct __attribute__((packed)) { u8 _pad_m340[0x344]; u8 m340[0x10]; };
    struct __attribute__((packed)) { u8 _pad_m350[0x354]; s32 m350; };
    struct __attribute__((packed)) { u8 _pad_m354[0x358]; f32 m354; };
    struct __attribute__((packed)) { u8 _pad_mRoomNo[0x35C]; s32 mRoomNo; };
    struct __attribute__((packed)) { u8 _pad_mRoomMapToolCameraIdx[0x360]; s32 mRoomMapToolCameraIdx; };
    struct __attribute__((packed)) { u8 _pad_m360[0x364]; u8 m360; };
    struct __attribute__((packed)) { u8 _pad__365[0x365]; u8 _365[3]; };
    struct __attribute__((packed)) { u8 _pad_m364[0x368]; s32 m364; };
    struct __attribute__((packed)) { u8 _pad_m368[0x36C]; f32 m368; };
    struct __attribute__((packed)) { u8 _pad_mWork[0x37C]; u8 mWork[0x80]; };
    struct __attribute__((packed)) { u8 _pad_mEventFlags[0x510]; u32 mEventFlags; };
    struct __attribute__((packed)) { u8 _pad_mCurStyle[0x514]; s32 mCurStyle; };
    struct __attribute__((packed)) { u8 _pad_m514[0x518]; s32 m514; };
    struct __attribute__((packed)) { u8 _pad_mCurType[0x51C]; s32 mCurType; };
    struct __attribute__((packed)) { u8 _pad_mNextType[0x520]; s32 mNextType; };
    struct __attribute__((packed)) { u8 _pad_mMapToolType[0x524]; s32 mMapToolType; };
    struct __attribute__((packed)) { u8 _pad_m524[0x528]; s32 m524; };
    struct __attribute__((packed)) { u8 _pad_m528[0x52C]; u32 m528; };
    struct __attribute__((packed)) { u8 _pad_m52C[0x530]; u8 m52C; };
    struct __attribute__((packed)) { u8 _pad__531[0x531]; u8 _531[3]; };
    struct __attribute__((packed)) { u8 _pad_m530[0x534]; s32 m530; };
    struct __attribute__((packed)) { u8 _pad_m534[0x538]; s16 m534; };
    struct __attribute__((packed)) { u8 _pad_m536[0x53A]; s16 m536; };
    struct __attribute__((packed)) { u8 _pad_m538[0x53C]; f32 m538; };
    struct __attribute__((packed)) { u8 _pad_m53C[0x540]; f32 m53C; };
    struct __attribute__((packed)) { u8 _pad_m540[0x544]; f32 m540; };
    struct __attribute__((packed)) { u8 _pad_m544[0x548]; u8 m544[4]; };
    struct __attribute__((packed)) { u8 _pad_m548[0x54C]; u8 m548[4]; };
    struct __attribute__((packed)) { u8 _pad_m54C[0x550]; u8 m54C[4]; };
    struct __attribute__((packed)) { u8 _pad_m550[0x554]; s32 m550; };
    struct __attribute__((packed)) { u8 _pad_m554[0x558]; s32 m554; };
    struct __attribute__((packed)) { u8 _pad_m558[0x55C]; u8 m558[4]; };
    struct __attribute__((packed)) { u8 _pad_mFovYShake[0x584]; f32 mFovYShake; };
    struct __attribute__((packed)) { u8 _pad__58A[0x58A]; u8 _58A[2]; };
    struct __attribute__((packed)) { u8 _pad_m588[0x58C]; s32 m588; };
    struct __attribute__((packed)) { u8 _pad_m58C[0x590]; s32 m58C; };
    struct __attribute__((packed)) { u8 _pad_mBlureTimer[0x594]; s32 mBlureTimer; };
    struct __attribute__((packed)) { u8 _pad_m59A[0x59E]; s16 m59A; };
    struct __attribute__((packed)) { u8 _pad_mBlurePositionType[0x5A0]; s32 mBlurePositionType; };
    struct __attribute__((packed)) { u8 _pad_mBlureAlpha[0x5BC]; f32 mBlureAlpha; };
    struct __attribute__((packed)) { u8 _pad__5C0[0x5C0]; u8 _5C0[4]; };
    struct __attribute__((packed)) { u8 _pad_mCurRoomCamEntry[0x5C4]; u8 mCurRoomCamEntry[0x14]; };
    struct __attribute__((packed)) { u8 _pad_mCurRoomArrowEntry[0x5D8]; u8 mCurRoomArrowEntry[0x14]; };
    struct __attribute__((packed)) { u8 _pad_mCurArrowIdx[0x5EC]; s32 mCurArrowIdx; };
    struct __attribute__((packed)) { u8 _pad_mWindowWidth[0x5F0]; f32 mWindowWidth; };
    struct __attribute__((packed)) { u8 _pad_mWindowHeight[0x5F4]; f32 mWindowHeight; };
    struct __attribute__((packed)) { u8 _pad_m5F4[0x5F8]; f32 m5F4; };
    struct __attribute__((packed)) { u8 _pad_mTrimHeight[0x5FC]; f32 mTrimHeight; };
    struct __attribute__((packed)) { u8 _pad_mTrimSize[0x600]; s32 mTrimSize; };
    struct __attribute__((packed)) { u8 _pad_mTrimTypeForce[0x604]; s32 mTrimTypeForce; };
    struct __attribute__((packed)) { u8 _pad_mWindowAspectRatio[0x608]; f32 mWindowAspectRatio; };
    struct __attribute__((packed)) { u8 _pad_m608[0x60C]; f32 m608; };
    struct __attribute__((packed)) { u8 _pad_mHD610[0x610]; u8 mHD610; };
    struct __attribute__((packed)) { u8 _pad__611[0x611]; u8 _611[3]; };
    struct __attribute__((packed)) { u8 _pad_mHDLookAtCamera[0x614]; u8 mHDLookAtCamera[0x58]; };
    struct __attribute__((packed)) { u8 _pad_mHDProjection[0x66C]; u8 mHDProjection[0xC4]; };
    struct __attribute__((packed)) { u8 _pad_mHD730[0x730]; u8 mHD730[8]; };
    struct __attribute__((packed)) { u8 _pad_mHD738[0x738]; u8 mHD738; };
    struct __attribute__((packed)) { u8 _pad__739[0x739]; u8 _739[3]; };
    struct __attribute__((packed)) { u8 _pad_mCamSetup[0x73C]; u8 mCamSetup[0x168]; };
    struct __attribute__((packed)) { u8 _pad_mCamParam[0x8A4]; u8 mCamParam[0xC]; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeField[0x8B0]; s32 mCamTypeField; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeEvent[0x8B4]; s32 mCamTypeEvent; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeWater[0x8B8]; s32 mCamTypeWater; };
    struct __attribute__((packed)) { u8 _pad_m768[0x8BC]; s32 m768; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeBoat[0x8C0]; s32 mCamTypeBoat; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeBoatBattle[0x8C4]; s32 mCamTypeBoatBattle; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeSubject[0x8C8]; s32 mCamTypeSubject; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeKeep[0x8CC]; s32 mCamTypeKeep; };
    struct __attribute__((packed)) { u8 _pad_mCamTypeRestrict[0x8D0]; s32 mCamTypeRestrict; };
} dCamera_c;
WWHD_SDK_ASSERT(sizeof(dCamera_c) == 0x8E0, "dCamera_c size");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mpCamera) == 0x0, "dCamera_c.mpCamera");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mActive) == 0x4, "dCamera_c.mActive");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mPause) == 0x5, "dCamera_c.mPause");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _036) == 0x36, "dCamera_c._036");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mFovy) == 0x38, "dCamera_c.mFovy");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m064) == 0x64, "dCamera_c.m064");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m068) == 0x68, "dCamera_c.m068");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _06E) == 0x6E, "dCamera_c._06E");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m07C) == 0x7C, "dCamera_c.m07C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m080) == 0x80, "dCamera_c.m080");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m09C) == 0x9C, "dCamera_c.m09C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _0A2) == 0xA2, "dCamera_c._0A2");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStageMapToolCameraIdx) == 0xE4, "dCamera_c.mStageMapToolCameraIdx");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m0E8) == 0xE8, "dCamera_c.m0E8");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _0F8) == 0xF8, "dCamera_c._0F8");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m100) == 0x100, "dCamera_c.m100");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m101) == 0x101, "dCamera_c.m101");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m102) == 0x102, "dCamera_c.m102");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _103) == 0x103, "dCamera_c._103");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m108) == 0x108, "dCamera_c.m108");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m10C) == 0x10C, "dCamera_c.m10C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m110) == 0x110, "dCamera_c.m110");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _111) == 0x111, "dCamera_c._111");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m114) == 0x114, "dCamera_c.m114");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m118) == 0x118, "dCamera_c.m118");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m11C) == 0x11C, "dCamera_c.m11C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCameraID) == 0x120, "dCamera_c.mCameraID");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mPadId) == 0x124, "dCamera_c.mPadId");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mpPlayerActor) == 0x128, "dCamera_c.mpPlayerActor");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mpLockonTarget) == 0x12C, "dCamera_c.mpLockonTarget");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mLockOnActorId) == 0x130, "dCamera_c.mLockOnActorId");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mpLockonActor) == 0x134, "dCamera_c.mpLockonActor");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mForceLockTimer) == 0x138, "dCamera_c.mForceLockTimer");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCurMode) == 0x13C, "dCamera_c.mCurMode");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mNextMode) == 0x140, "dCamera_c.mNextMode");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m144) == 0x144, "dCamera_c.m144");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _14A) == 0x14A, "dCamera_c._14A");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m14C) == 0x14C, "dCamera_c.m14C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m150) == 0x150, "dCamera_c.m150");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m154) == 0x154, "dCamera_c.m154");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickMainPosXLast) == 0x158, "dCamera_c.mStickMainPosXLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickMainPosYLast) == 0x15C, "dCamera_c.mStickMainPosYLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickMainValueLast) == 0x160, "dCamera_c.mStickMainValueLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickMainPosXDelta) == 0x164, "dCamera_c.mStickMainPosXDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickMainPosYDelta) == 0x168, "dCamera_c.mStickMainPosYDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickMainValueDelta) == 0x16C, "dCamera_c.mStickMainValueDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickCPosXLast) == 0x170, "dCamera_c.mStickCPosXLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickCPosYLast) == 0x174, "dCamera_c.mStickCPosYLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickCValueLast) == 0x178, "dCamera_c.mStickCValueLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickCPosXDelta) == 0x17C, "dCamera_c.mStickCPosXDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickCPosYDelta) == 0x180, "dCamera_c.mStickCPosYDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mStickCValueDelta) == 0x184, "dCamera_c.mStickCValueDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m184) == 0x188, "dCamera_c.m184");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m188) == 0x18C, "dCamera_c.m188");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m18C) == 0x190, "dCamera_c.m18C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTriggerLeftLast) == 0x194, "dCamera_c.mTriggerLeftLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTriggerLeftDelta) == 0x198, "dCamera_c.mTriggerLeftDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHoldLockL) == 0x19C, "dCamera_c.mHoldLockL");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrigLockL) == 0x19D, "dCamera_c.mTrigLockL");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m19A) == 0x19E, "dCamera_c.m19A");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m19B) == 0x19F, "dCamera_c.m19B");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTriggerRightLast) == 0x1A0, "dCamera_c.mTriggerRightLast");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTriggerRightDelta) == 0x1A4, "dCamera_c.mTriggerRightDelta");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHoldLockR) == 0x1A8, "dCamera_c.mHoldLockR");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrigLockR) == 0x1A9, "dCamera_c.mTrigLockR");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m1A6) == 0x1AA, "dCamera_c.m1A6");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m1A7) == 0x1AB, "dCamera_c.m1A7");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHoldX) == 0x1AC, "dCamera_c.mHoldX");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrigX) == 0x1AD, "dCamera_c.mTrigX");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHoldY) == 0x1AE, "dCamera_c.mHoldY");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrigY) == 0x1AF, "dCamera_c.mTrigY");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHoldZ) == 0x1B0, "dCamera_c.mHoldZ");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrigZ) == 0x1B1, "dCamera_c.mTrigZ");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m1AE) == 0x1B2, "dCamera_c.m1AE");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m1AF) == 0x1B3, "dCamera_c.m1AF");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _22A) == 0x22A, "dCamera_c._22A");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m248) == 0x24C, "dCamera_c.m248");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m254) == 0x258, "dCamera_c.m254");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m258) == 0x25C, "dCamera_c.m258");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m314) == 0x318, "dCamera_c.m314");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _319) == 0x319, "dCamera_c._319");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m318) == 0x31C, "dCamera_c.m318");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m31C) == 0x320, "dCamera_c.m31C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m31D) == 0x321, "dCamera_c.m31D");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _322) == 0x322, "dCamera_c._322");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m33C) == 0x340, "dCamera_c.m33C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m340) == 0x344, "dCamera_c.m340");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m350) == 0x354, "dCamera_c.m350");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m354) == 0x358, "dCamera_c.m354");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mRoomNo) == 0x35C, "dCamera_c.mRoomNo");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mRoomMapToolCameraIdx) == 0x360, "dCamera_c.mRoomMapToolCameraIdx");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m360) == 0x364, "dCamera_c.m360");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _365) == 0x365, "dCamera_c._365");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m364) == 0x368, "dCamera_c.m364");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m368) == 0x36C, "dCamera_c.m368");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mWork) == 0x37C, "dCamera_c.mWork");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mEventFlags) == 0x510, "dCamera_c.mEventFlags");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCurStyle) == 0x514, "dCamera_c.mCurStyle");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m514) == 0x518, "dCamera_c.m514");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCurType) == 0x51C, "dCamera_c.mCurType");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mNextType) == 0x520, "dCamera_c.mNextType");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mMapToolType) == 0x524, "dCamera_c.mMapToolType");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m524) == 0x528, "dCamera_c.m524");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m528) == 0x52C, "dCamera_c.m528");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m52C) == 0x530, "dCamera_c.m52C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _531) == 0x531, "dCamera_c._531");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m530) == 0x534, "dCamera_c.m530");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m534) == 0x538, "dCamera_c.m534");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m536) == 0x53A, "dCamera_c.m536");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m538) == 0x53C, "dCamera_c.m538");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m53C) == 0x540, "dCamera_c.m53C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m540) == 0x544, "dCamera_c.m540");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m544) == 0x548, "dCamera_c.m544");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m548) == 0x54C, "dCamera_c.m548");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m54C) == 0x550, "dCamera_c.m54C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m550) == 0x554, "dCamera_c.m550");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m554) == 0x558, "dCamera_c.m554");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m558) == 0x55C, "dCamera_c.m558");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mFovYShake) == 0x584, "dCamera_c.mFovYShake");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _58A) == 0x58A, "dCamera_c._58A");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m588) == 0x58C, "dCamera_c.m588");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m58C) == 0x590, "dCamera_c.m58C");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mBlureTimer) == 0x594, "dCamera_c.mBlureTimer");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m59A) == 0x59E, "dCamera_c.m59A");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mBlurePositionType) == 0x5A0, "dCamera_c.mBlurePositionType");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mBlureAlpha) == 0x5BC, "dCamera_c.mBlureAlpha");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _5C0) == 0x5C0, "dCamera_c._5C0");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCurRoomCamEntry) == 0x5C4, "dCamera_c.mCurRoomCamEntry");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCurRoomArrowEntry) == 0x5D8, "dCamera_c.mCurRoomArrowEntry");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCurArrowIdx) == 0x5EC, "dCamera_c.mCurArrowIdx");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mWindowWidth) == 0x5F0, "dCamera_c.mWindowWidth");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mWindowHeight) == 0x5F4, "dCamera_c.mWindowHeight");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m5F4) == 0x5F8, "dCamera_c.m5F4");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrimHeight) == 0x5FC, "dCamera_c.mTrimHeight");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrimSize) == 0x600, "dCamera_c.mTrimSize");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mTrimTypeForce) == 0x604, "dCamera_c.mTrimTypeForce");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mWindowAspectRatio) == 0x608, "dCamera_c.mWindowAspectRatio");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m608) == 0x60C, "dCamera_c.m608");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHD610) == 0x610, "dCamera_c.mHD610");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _611) == 0x611, "dCamera_c._611");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHDLookAtCamera) == 0x614, "dCamera_c.mHDLookAtCamera");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHDProjection) == 0x66C, "dCamera_c.mHDProjection");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHD730) == 0x730, "dCamera_c.mHD730");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mHD738) == 0x738, "dCamera_c.mHD738");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, _739) == 0x739, "dCamera_c._739");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamSetup) == 0x73C, "dCamera_c.mCamSetup");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamParam) == 0x8A4, "dCamera_c.mCamParam");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeField) == 0x8B0, "dCamera_c.mCamTypeField");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeEvent) == 0x8B4, "dCamera_c.mCamTypeEvent");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeWater) == 0x8B8, "dCamera_c.mCamTypeWater");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, m768) == 0x8BC, "dCamera_c.m768");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeBoat) == 0x8C0, "dCamera_c.mCamTypeBoat");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeBoatBattle) == 0x8C4, "dCamera_c.mCamTypeBoatBattle");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeSubject) == 0x8C8, "dCamera_c.mCamTypeSubject");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeKeep) == 0x8CC, "dCamera_c.mCamTypeKeep");
WWHD_SDK_ASSERT(__builtin_offsetof(dCamera_c, mCamTypeRestrict) == 0x8D0, "dCamera_c.mCamTypeRestrict");
