"""Public, game-free translation fixture for desktop and embedded Android Python.

Run with --output DIR to emit synthetic RPX, translated C and a native harness.
Pass --reference DIR to compare every C/header byte against a desktop run.
This module uses no subprocesses, so the Android embedding can invoke main().
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
import time


def synthetic_rpx():
    """ELF32 big endian: li r3,40; addi r3,r3,2; blr (return 42)."""
    names = b"\0.text\0.shstrtab\0"
    code = struct.pack(">3I", 0x38600028, 0x38630002, 0x4E800020)
    data = bytearray(52 + 3 * 40)
    data[:16] = b"\x7fELF\x01\x02\x01" + bytes(9)
    struct.pack_into(">HHIIIIIHHHHHH", data, 16,
                     2, 20, 1, 0x02000000, 0, 52, 0, 52, 0, 0, 40, 3, 2)
    struct.pack_into(">10I", data, 92, 1, 1, 6, 0x02000000,
                     len(data), len(code), 0, 0, 4, 0)
    struct.pack_into(">10I", data, 132, 7, 3, 0, 0,
                     len(data) + len(code), len(names), 0, 0, 1, 0)
    return bytes(data) + code + names


HARNESS = r'''#include "funcs.h"
#include <stdlib.h>
int g_ppc_trace = 0;
volatile int g_core_preempt[3] = {0};
void ppc_trace_enter(uint32_t a) { (void)a; }
void ppc_preempt(Cpu* c) { (void)c; }
void ppc_unimplemented(Cpu* c, uint32_t a, uint32_t i) {
    (void)c; (void)a; (void)i; abort();
}
int main(void) {
    Cpu cpu = {0};
    f_02000000(&cpu);
    return cpu.r[3] == 42 ? 0 : 1;
}
'''


def inventory(directory):
    return {p.name: p.read_bytes() for p in sorted(directory.iterdir())
            if p.suffix in (".c", ".h")}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--reference", type=Path)
    args = parser.parse_args(argv)
    # Import the real recompiler, with its normal hooks and instruction emitter.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from recomp import Recompiler

    args.output.mkdir(parents=True, exist_ok=True)
    fixture = args.output / "synthetic.rpx"
    fixture.write_bytes(synthetic_rpx())
    generated = args.output / "gen"
    # Refuse stale outputs: otherwise a removed source could escape parity checks.
    if generated.exists():
        raise ValueError("use a fresh output directory: " + str(generated))
    start = time.monotonic()
    Recompiler(str(fixture)).run(str(generated), 30000)
    elapsed = time.monotonic() - start
    (generated / "harness.c").write_text(HARNESS, encoding="utf-8")
    actual = inventory(generated)
    if args.reference:
        expected = inventory(args.reference / "gen")
        if actual.keys() != expected.keys():
            raise AssertionError("generated C/header inventory differs")
        for name, content in actual.items():
            if content != expected[name]:
                raise AssertionError("generated bytes differ: " + name)
    metrics = {
        "fixture": "synthetic-return-42-v1", "python": sys.version,
        "translation_seconds": elapsed,
        "generated_bytes": sum(map(len, actual.values())),
        "sha256": {name: hashlib.sha256(content).hexdigest()
                   for name, content in actual.items()},
    }
    (args.output / "metrics.json").write_text(
        json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    return metrics


if __name__ == "__main__":
    print(json.dumps(main(), indent=2))
